---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: azure-storage-exporter
  namespace: monitoring
  labels:
    app: azure-storage-exporter
spec:
  selector:
    matchLabels:
      app: azure-storage-exporter
  podMetricsEndpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 30s
    path: /metrics



